version: "3.4"
services:
    culturio-users:
        image: users
        build:
          context: .
          dockerfile: Span.Culturio.Users/Dockerfile
        environment:
          - "ASPNETCORE_ENVIRONMENT=Development"
          - "ASPNETCORE_URLS=http://+:80"
          - "ConnectionStrings__DefaultConnection=Server=culturio-users-db,1443;Database=Culturio.Users;User Id=sa;Password=MyPass@word"
        ports:
          - "5000:80"
        depends_on:
          - culturio-users-db
    culturio-auth:
        image: auth
        build:
          context: .
          dockerfile: Span.Culturio.Auth/Dockerfile
        environment:
          - "ASPNETCORE_ENVIRONMENT=Development"
          - "ASPNETCORE_URLS=http://+:80"
          - "ConnectionStrings__DefaultConnection=Server=culturio-users-db,1443;Database=Culturio.Users;User Id=sa;Password=MyPass@word"
        ports:
          - "5001:80"
        depends_on:
          - culturio-users-db
    culturio-users-db:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        ports:
          - "1443:1433"
        environment:
            SA_PASSWORD: "MyPass@word"
            ACCEPT_EULA: "Y"
    culturio-cultureobjects:
        image: cultureobjects
        build:
            context: .
            dockerfile: Span.Culturio.CultureObjects/Dockerfile
        environment:
            - "ASPNETCORE_ENVIRONMENT=Development"
            - "ASPNETCORE_URLS=http://+:80"
            - "ConnectionStrings__DefaultConnection=Server=culturio-cultureObject-db;Database=Culturio.CultureObjects;User Id=sa;Password=MyPass@word"
        ports:
            - "5002:80"
        depends_on:
            - culturio-cultureobjects-db
    culturio-cultureobjects-db:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        ports:
            - "1444:1433"
        environment:
            SA_PASSWORD: "MyPass@word"
            ACCEPT_EULA: "Y"
    culturio-packages:
        image: packages
        build:
            context: .
            dockerfile: Span.Culturio.Packages/Dockerfile
        environment:
            - "ASPNETCORE_ENVIRONMENT=Development"
            - "ASPNETCORE_URLS=http://+:80"
            - "ConnectionStrings__DefaultConnection=Server=culturio-packages-db;Database=Culturio.Packages;User Id=sa;Password=MyPass@word"
        ports:
            - "5003:80"
        depends_on:
            - culturio-packages-db
    culturio-packages-db:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        ports:
            - "1445:1433"
        environment:
            SA_PASSWORD: "MyPass@word"
            ACCEPT_EULA: "Y"
            
    